// JSON array of projects
const projects = [
    {
        id: 1,
        title: "Task 1 Expectation document",
        date: "2025",
        description: "Course expectations and requirements",
        fileType: "txt",
        technologies: ["Text"],
        features: ["Documentation"],
        path: "task 1.txt",
        demo: "task 1.txt",
        code: "#"
    },
    {
        id: 2,
        title: "Task 2 Basic HTML styling",
        date: "2025",
        description: "HTML and CSS fundamentals",
        fileType: "html",
        technologies: ["HTML", "CSS"],
        features: ["Styling basics"],
        path: "task 2.html",
        demo: "task 2.html",
        code: "#"
    },
    {
        id: 3,
        title: "Task 3 CSS Hover",
        date: "2025",
        description: "CSS hover effects implementation",
        fileType: "html",
        technologies: ["HTML", "CSS"],
        features: ["Interactive elements"],
        path: "task 3.html",
        demo: "task 3.html",
        code: "#"
    },
    {
        id: 4,
        title: "Task 4 Welcome to JS",
        date: "2025",
        description: "Introduction to JavaScript",
        fileType: "html",
        technologies: ["HTML", "CSS", "JavaScript"],
        features: ["Basic scripting"],
        path: "task 4.html",
        demo: "task 4.html",
        code: "#"
    },
    {
        id: 5,
        title: "Task 5 Calculator with js",
        date: "2025",
        description: "JavaScript calculator implementation",
        fileType: "html",
        technologies: ["HTML", "CSS", "JavaScript"],
        features: ["Calculations", "User input"],
        path: "task 5.html",
        demo: "task 5.html",
        code: "#"
    },
    {
        id: 6,
        title: "Task 6 GitHub integration",
        date: "2025",
        description: "Using GitHub for version control",
        fileType: "txt",
        technologies: ["Git", "GitHub"],
        features: ["Version control"],
        path: "task 6.txt",
        demo: "task 6.txt",
        code: "#"
    },
    {
        id: 7,
        title: "Task 7 Console output",
        date: "2025",
        description: "Working with browser console",
        fileType: "txt",
        technologies: ["JavaScript"],
        features: ["Debugging"],
        path: "task 7.txt",
        demo: "task 7.txt",
        code: "#"
    },
    {
        id: 8,
        title: "Task 8 String operation",
        date: "2025",
        description: "JavaScript string manipulation",
        fileType: "html",
        technologies: ["JavaScript"],
        features: ["Text processing"],
        path: "task 8.html",
        demo: "task 8.html",
        code: "#"
    },
    {
        id: 9,
        title: "Task 9 Conditions",
        date: "2025",
        description: "JavaScript conditional statements",
        fileType: "html",
        technologies: ["JavaScript"],
        features: ["Control flow"],
        path: "task 9.html",
        demo: "task 9.html",
        code: "#"
    },
    {
        id: 10,
        title: "Task 10 call stack with array",
        date: "2025",
        description: "JavaScript call stack and arrays",
        fileType: "html",
        technologies: ["JavaScript"],
        features: ["Advanced concepts"],
        path: "task 10.html",
        demo: "task 10.html",
        code: "#"
    },
    {
        id: 11,
        title: "Task 11 star with loops",
        date: "2025",
        description: "Pattern generation using loops",
        fileType: "html",
        technologies: ["JavaScript"],
        features: ["Loop implementation"],
        path: "task 11.html",
        demo: "task 11.html",
        code: "#"
    },
    {
        id: 12,
        title: "Task 12 class work",
        date: "2025",
        description: "Introduction to JavaScript classes",
        fileType: "html",
        technologies: ["JavaScript", "OOP"],
        features: ["Object-oriented programming"],
        path: "task 12.html",
        demo: "task 12.html",
        code: "#"
    },
    {
        id: 13,
        title: "Task 13 class work objects",
        date: "2025",
        description: "Working with JavaScript objects",
        fileType: "html",
        technologies: ["JavaScript", "OOP"],
        features: ["Object-oriented programming"],
        path: "task 13.html",
        demo: "task 12.html",
        code: "#"
    },
    {
        id: 14,
        title: "Task 14 class work objects 2",
        date: "2025",
        description: "Advanced JavaScript objects",
        fileType: "zip",
        technologies: ["JavaScript", "OOP"],
        features: ["Advanced OOP concepts"],
        path: "task 14.zip",
        demo: "#",
        code: "#"
    },
    {
        id: 15,
        title: "Task 15 class & Bootstrap",
        date: "2025",
        description: "Using Bootstrap with JavaScript classes",
        fileType: "zip",
        technologies: ["JavaScript", "Bootstrap", "OOP"],
        features: ["UI frameworks"],
        path: "task 15.zip",
        demo: "#",
        code: "#"
    },
    {
        id: 16,
        title: "Task 16 class work JSON",
        date: "2025",
        description: "Working with JSON in JavaScript",
        fileType: "txt",
        technologies: ["JavaScript", "JSON"],
        features: ["Data interchange"],
        path: "task 16.txt",
        demo: "task 16.txt",
        code: "#"
    }
];
